title: rhbi-auk
author: rhbi-auk
remote_theme: daattali/beautiful-jekyll

navbar-links:
  Sheet Music: "sheet-music"
  Takadimi: "takadimi"
  About: "about"

social-network-links:
  email: "reginabi@outlook.co.nz"
  github: rhbi-auk

avatar: "/assets/img/number cruncher.png"
round-avatar: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

site-js:
  - "/assets/js/disclaimer.js"