title: Sheet Music
author: rhbi-auk
remote_theme: daattali/beautiful-jekyll

navbar-links:
  Persona: "persona"
  RWBY: "rwby"

social-network-links:
  email: "reginabi@outlook.co.nz"
  github: rhbi-auk

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme