title: My Projects
author: rhbi-auk
remote_theme: daattali/beautiful-jekyll

navbar-links:
  Sheet Music:
    - Persona: "persona"
    - RWBY: "rwby"
  Takadimi: "takadimi"
  About: "about"

social-network-links:
  email: "reginabi@outlook.co.nz"
  github: rhbi-auk

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

site-js:
  - "/Sheet-Music/assets/js/disclaimer.js"